// Crypto identity, QR pairing payloads, invite links.
// Included by api/frb.rs (include!, not a module): items must stay in
// crate::api::frb so the generated bindings keep their names, and file order
// mirrors the include! order because the generated Dart facade follows
// declaration order. Shared imports live in frb.rs.

// ============ E2EE Identity & Key Exchange (FFI) ============

/// Global identity service (initialized once, similar to DB)
static IDENTITY_SERVICE: OnceLock<crate::services::IdentityService> = OnceLock::new();

/// Initialize the node's cryptographic identity.
/// Must be called after init_backend and after obtaining the library UUID.
/// Uses Argon2(library_uuid) to encrypt/decrypt the stored keypair.
///
/// Errors propagate through `IdentityError::Display`, which prefixes the
/// `DecryptionFailed` variant with `E_IDENTITY_DECRYPT_FAILED` so the Flutter
/// layer can pattern-match the FFI exception and surface a recovery dialog
/// instead of silently regenerating the identity (which would break peers).
pub async fn init_identity_ffi(library_uuid: String) -> Result<String, String> {
    let db_conn = db().ok_or("Database not initialized")?;

    let svc =
        IDENTITY_SERVICE.get_or_init(|| crate::services::IdentityService::new(db_conn.clone()));

    svc.init(&library_uuid).await.map_err(|e| e.to_string())?;
    Ok("Identity initialized".to_string())
}

/// User-confirmed identity regeneration: wipes `crypto_keys` and runs init.
///
/// Called by the Flutter recovery dialog when the user explicitly chooses
/// "Régénérer (perdre les peers)". Every paired peer (iPhone, Android, etc.)
/// will have to re-pair after this — that's the expected cost.
pub async fn confirm_regenerate_identity_ffi(library_uuid: String) -> Result<String, String> {
    let db_conn = db().ok_or("Database not initialized")?;

    crate::services::identity_service::delete_identity_from_db(db_conn).await?;

    let svc =
        IDENTITY_SERVICE.get_or_init(|| crate::services::IdentityService::new(db_conn.clone()));

    svc.init(&library_uuid).await.map_err(|e| e.to_string())?;
    tracing::warn!("E2EE identity regenerated by user confirmation; peers will need to re-pair");
    Ok("Identity regenerated".to_string())
}

/// Get the node's public keys as JSON: {"ed25519": "hex...", "x25519": "hex..."}
pub async fn get_public_keys_ffi() -> Result<String, String> {
    let svc = IDENTITY_SERVICE.get().ok_or("Identity not initialized")?;

    let (ed25519, x25519) = svc.get_public_keys_hex()?;
    Ok(serde_json::json!({
        "ed25519": ed25519,
        "x25519": x25519,
    })
    .to_string())
}

/// Generate a QR v2 payload as JSON string.
/// Includes library name, URL, UUID, and public keys.
pub async fn generate_qr_payload_ffi(
    library_name: String,
    url: String,
    library_uuid: String,
) -> Result<String, String> {
    let svc = IDENTITY_SERVICE.get().ok_or("Identity not initialized")?;

    let (ed25519, x25519) = svc.get_public_keys_hex()?;

    let payload = serde_json::json!({
        "version": 2,
        "name": library_name,
        "url": url,
        "library_uuid": library_uuid,
        "ed25519_public_key": ed25519,
        "x25519_public_key": x25519,
    });

    Ok(payload.to_string())
}

/// Parse a QR payload (supports both v1 and v2 formats).
/// Returns a normalized JSON string with all available fields.
pub async fn parse_qr_payload_ffi(payload: String) -> Result<String, String> {
    let parsed: serde_json::Value =
        serde_json::from_str(&payload).map_err(|e| format!("Invalid QR JSON: {e}"))?;

    // Check for version field to determine format
    let version = parsed.get("version").and_then(|v| v.as_i64()).unwrap_or(1);

    let result = if version >= 2 {
        // QR v2: full payload with keys
        parsed
    } else {
        // QR v1: legacy format with just name + url
        serde_json::json!({
            "version": 1,
            "name": parsed.get("name").and_then(|v| v.as_str()).unwrap_or(""),
            "url": parsed.get("url").and_then(|v| v.as_str()).unwrap_or(""),
        })
    };

    Ok(result.to_string())
}

/// Generate an invite link with the library's connection info encoded in the URL fragment.
/// Format: https://bibliogenius.org/invite#BASE64URL(json)
/// The fragment (#) is never sent to the web server (B8 compliance).
/// Payload v3 adds optional relay info for WAN connectivity.
pub async fn generate_invite_link_ffi(
    library_name: String,
    url: String,
    library_uuid: String,
    relay_url: Option<String>,
    mailbox_id: Option<String>,
    relay_write_token: Option<String>,
) -> Result<String, String> {
    use base64::Engine;

    let svc = IDENTITY_SERVICE.get().ok_or("Identity not initialized")?;

    let (ed25519, x25519) = svc.get_public_keys_hex()?;

    let mut payload = serde_json::json!({
        "version": 3,
        "name": library_name,
        "url": url,
        "library_uuid": library_uuid,
        "ed25519_public_key": ed25519,
        "x25519_public_key": x25519,
    });

    // Include relay info if available (for WAN connectivity)
    if let Some(ref r) = relay_url {
        payload["relay_url"] = serde_json::Value::String(r.clone());
    }
    if let Some(ref m) = mailbox_id {
        payload["mailbox_id"] = serde_json::Value::String(m.clone());
    }
    if let Some(ref t) = relay_write_token {
        payload["relay_write_token"] = serde_json::Value::String(t.clone());
    }

    let json_bytes = payload.to_string().into_bytes();
    let encoded = base64::engine::general_purpose::URL_SAFE_NO_PAD.encode(&json_bytes);

    Ok(format!("https://bibliogenius.org/invite#{encoded}"))
}

/// Parse an invite link, extracting the JSON payload from the URL fragment.
pub async fn parse_invite_link_ffi(link: String) -> Result<String, String> {
    use base64::Engine;

    let fragment = link
        .split_once('#')
        .map(|(_, f)| f)
        .ok_or("Invalid invite link: no fragment")?;

    let decoded = base64::engine::general_purpose::URL_SAFE_NO_PAD
        .decode(fragment)
        .map_err(|e| format!("Invalid base64 in invite link: {e}"))?;

    let json_str =
        String::from_utf8(decoded).map_err(|e| format!("Invalid UTF-8 in invite link: {e}"))?;

    // Validate it's valid JSON
    let _: serde_json::Value =
        serde_json::from_str(&json_str).map_err(|e| format!("Invalid JSON in invite: {e}"))?;

    // Re-parse to normalize (same as QR parse for consistency)
    parse_qr_payload_ffi(json_str).await
}
